---
- hosts: all
  become: true
  become_method: sudo
  vars_files:
    - vars/server.yml
    - vars/apache.yml
    - vars/mariadb.yml
    - vars/php.yml
    - vars/redis.yml
    - vars/node.yml
  roles:
    - server
    - supervisor
    - mariadb
    - apache
    - php
    - memcached
    - redis
    - node
    - app