- name: Download Composer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-installer.php
    mode: 0440

- name: Install Composer
  shell: "{{ item }}"
  with_items:
    - php /tmp/composer-installer.php --install-dir=/tmp
    - mv /tmp/composer.phar /usr/local/bin/composer
    - rm /tmp/composer-installer.php

- name: Install global Composer packages
  become: false
  shell: composer global require "{{ item }}"
  with_items:
    - laravel/installer
    - laravel/lumen-installer
    - phpunit/phpunit ~6.0

- name: Include Composer bin directory in PATH
  lineinfile: dest="/home/vagrant/.profile" line="PATH=~/.config/composer/vendor/bin:$PATH" state="present" insertafter="EOF"
