##################################################
# Generated by phansible.com (edited by marlek)
##################################################

provider_name = "My Ansible"
server_ip     = "192.168.99.20"
server_memory = "512" # MB
hostname      = "development.local"

# Check to determine whether we're on a windows or linux/os-x host,
# later on we use this to launch ansible in the supported way
# source: https://stackoverflow.com/questions/2108727/which-in-ruby-checking-if-program-exists-in-path-from-ruby
def which(cmd)
    exts = ENV['PATHEXT'] ? ENV['PATHEXT'].split(';') : ['']
    ENV['PATH'].split(File::PATH_SEPARATOR).each do |path|
        exts.each { |ext|
            exe = File.join(path, "#{cmd}#{ext}")
            return exe if File.executable? exe
        }
    end
    return nil
end
Vagrant.configure("2") do |config|

    config.vm.provider :virtualbox do |v|
        v.name = provider_name
        v.customize ["modifyvm", :id, "--memory", server_memory]
    end

    config.vm.box = "hashicorp/precise64"

    config.vm.box_url = "https://vagrantcloud.com/hashicorp/precise64/version/2/provider/virtualbox.box"

    config.vm.hostname = hostname

    config.vm.network :private_network, ip: server_ip
    config.ssh.forward_agent = true

    # Port forwarding. Be sure to forward 80 -> 8080 on host with the ipfw command below.
    # This is necessary because you cant forward 80 on host to 80 on guest because of Unix port permissions
    # sudo ipfw add 80 fwd 127.0.0.1,8080 tcp from any to me 80
    config.vm.network :forwarded_port, guest: 80, host: 8080

    #############################################################
    # Ansible provisioning (you need to have ansible installed)
    #############################################################


    if which('ansible-playbook')
        config.vm.provision "ansible" do |ansible|
            ansible.playbook = "ansible/playbook.yml"
            ansible.inventory_path = "ansible/inventories/dev"
            ansible.limit = 'all'
        end
    else
        config.vm.provision :shell, path: "ansible/windows.sh"
    end


    config.vm.synced_folder "~/Projects", "/vagrant", type: "nfs"
end
