---
# Retrieve the current hostname, because {{ ansible_hostname }} still contains the old name
- shell: hostname
  register: current_hostname

- name: Add PGP key for MySQL
  apt_key:
    keyserver: "{{mysql.key_server}}"
    id: "{{mysql.key_id}}"

- name: Add ppa Repository for MySQL
  apt_repository:
    repo: "{{mysql.ppa}}"
    state: present

- name: Update apt
  apt: update_cache=yes

- name: mysql | Install MySQL Packages
  apt:
    pkg: "{{mysql.packages}}"
    state: latest
  when: mysql.packages is defined

- name: mysql | Update root password for all root accounts
  mysql_user: name=root host={{ item }} check_implicit_admin=yes password={{ mysql.root_password }} login_user=root login_password={{ mysql.root_password }}
  with_items:
    - "{{ current_hostname.stdout | lower }}"
    - 127.0.0.1
    - ::1
    - localhost