---
- hosts: all
  become: true
  become_method: sudo
  vars_files:
    - vars/all.yml
  roles:
    - server
    - apache
    - mysql
    - php
    - xdebug
    - composer
    - memcached
    - node
    - app
