---
# Retrieve the current hostname, because {{ ansible_hostname }} still contains the old name
- shell: hostname
  register: current_hostname

- name: Add ppa Repository for MySQL
  apt_repository: repo=ppa:ondrej/mysql-{{ mysql.version }}

- name: mysql | Install MySQL Packages
  apt:
    pkg: ['mysql-server-{{ mysql.version }}', 'mysql-client-{{ mysql.version }}', 'python-mysqldb']
    state: latest

- name: mysql | Update root password for all root accounts
  mysql_user: name=root host={{ item }} check_implicit_admin=yes password={{ mysql.root_password }} login_user=root login_password={{ mysql.root_password }}
  with_items:
    - "{{ current_hostname.stdout | lower }}"
    - 127.0.0.1
    - ::1
    - localhost
