---
# Retrieve the current hostname, because {{ ansible_hostname }} still contains the old name
- shell: hostname
  register: current_hostname

- name: Add key for Mariadb
  command: "apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 0xcbcb082a1bb943db"

- name: Add ppa Repository for Mariadb
  apt_repository:
    repo: "deb [arch=amd64,i386] http://www.ftp.saix.net/DB/mariadb/repo/{{ mysql.mariadb_version }}/debian wheezy main"
    state: present

- name: Update apt
  apt: update_cache=yes

- name: mysql | Install MySQL Packages
  apt: pkg={{ item }} state=latest
  with_items: "{{mysql.packages}}"
  when: mysql.packages is defined

- name: mysql | Update root password for all root accounts
  mysql_user: name=root host={{ item }} check_implicit_admin=yes password={{ mysql.root_password }} login_user=root login_password={{ mysql.root_password }}
  with_items:
    - "{{ current_hostname.stdout | lower }}"
    - 127.0.0.1
    - ::1
    - localhost