---
- name: ensure timezone is set in apache2 php.ini
  lineinfile: dest=/etc/php/5.6/apache2/php.ini
              regexp='date.timezone ='
              line='date.timezone = {{ server.timezone }}'

- name: disabling opcache
  lineinfile: dest=/etc/php/5.6/apache2/php.ini
              regexp=';?opcache.enable=\d'
              line='opcache.enable=0'
