---
- name: ensure timezone is set in cli php.ini
  lineinfile: dest=/etc/php/5.6/cli/php.ini
              regexp='date.timezone ='
              line='date.timezone = {{ server.timezone }}'

- name: disabling opcache cli
  lineinfile: dest=/etc/php/5.6/cli/php.ini
              regexp=';?opcache.enable_cli=\d'
              line='opcache.enable_cli=0'
