---
server:
    packages: [vim, git, htop, imagemagick, curl, wget, python-software-properties]
    timezone: UTC
    locale: en_US.UTF-8
apache:
    docroot: /var/www
    servername: www.default.dev
mysql:
    version: '5.6'
    root_password: 'root'
php:
    ppa: php
    packages: [
        php5.6-cli,
        php5.6-common,
        php5.6-curl,
        php5.6-dev,
        php5.6-gd,
        php5.6-imap,
        php5.6-intl,
        php5.6-json,
        php5.6-mcrypt,
        php5.6-mysql,
        php5.6-opcache,
        php5.6-pgsql,
        php5.6-readline,
        php5.6-sqlite3,
        php5.6-zip,
        php5.6-mbstring,
        php5.6-xml,
        php-imagick,
        libapache2-mod-php5.6
    ]
node:
    node_version: '10'
    global_packages: ['grunt-cli', 'gulp', 'yo', 'bower']
