---
    php_ppa: php5-oldstable
    doc_root: /var/www
    sys_packages: ["vim","git","imagemagick","htop"]
    dist: precise
    php_packages: ["php5-cli","php5-curl","php5-imagick","php5-mcrypt","php5-memcached","php5-sqlite","php5-xdebug"]
