---

- name: Add ppa Repository for PHP
  apt_repository: repo=ppa:ondrej/{{ php.ppa }}

- name: Update apt
  apt: update_cache=yes

- name: Install Extra Packages
  apt:
    pkg: "{{server.packages}}"
    state: latest
  when: server.packages is defined

- name: Configure the timezone
  template: src=timezone.tpl dest=/etc/timezone

- name: More Configure the timezone
  file: src=/usr/share/zoneinfo/{{server.timezone}} dest=/etc/localtime state=link force=yes backup=yes

- name: Set default system language pack
  shell: locale-gen {{server.locale}}
