---
- name: Update apt
  apt: update_cache=yes

- name: Configure the timezone
  template: src=timezone.tpl dest=/etc/timezone

- name: More Configure the timezone
  file: src=/usr/share/zoneinfo/{{server.timezone}} dest=/etc/localtime state=link force=yes

- name: Set default system language pack
  shell: locale-gen {{server.locale}}

- name: Set default locale
  shell: export LC_ALL=en_US.UTF-8 && export LANG=en_US.UTF-8

- name: Allow ssh connection with plain text passwords
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^#PasswordAuthentication yes$'
    line: 'PasswordAuthentication yes'
    backrefs: yes
  notify: restart ssh

- name: Install System Packages
  apt:
    pkg: "{{server.packages}}"
    state: latest
  when: server.packages is defined