---
- name: "Checkout nvm repository"
  git: repo="https://github.com/creationix/nvm.git" dest="{{ homedir }}/.nvm" accept_hostkey="yes" update="yes"
  sudo: yes
  sudo_user: "{{ user }}"

- name: "Installing nodejs"
  shell: source {{ homedir }}/.nvm/nvm.sh && nvm install {{ item.node_version }}
         executable="/bin/bash"
  with_items: node
  sudo: yes
  sudo_user: "{{ user }}"

- name: "Activating default version"
  shell: source {{ homedir }}/.nvm/nvm.sh && nvm alias default {{ item.node_version }}
         executable="/bin/bash"
  with_items: node
  sudo: yes
  sudo_user: "{{ user }}"

- name: "Ensure nvm is loaded during login"
  lineinfile: dest="{{ homedir }}/.profile" line="source {{ homedir }}/.nvm/nvm.sh" state="present" insertafter="EOF"

- name: "Installing global npm packages"
  shell: source {{ homedir }}/.nvm/nvm.sh && nvm use {{ item.0.node_version }} && npm install -g '{{ item.1 }}'
         executable="/bin/bash"
  with_subelements:
    - node
    - global_packages
  sudo: yes
  sudo_user: "{{ user }}"