---
- hosts: all
  sudo: true
  vars:
    web_server: apachephp
    servername: default.dev www.default.dev
    timezone: UTC
    user: vagrant
    homedir: /home/vagrant
  vars_files:
    - vars/mysql.yml
    - vars/common.yml
    - vars/node.yml
    - [ "vars/apachephp.yml", "vars/ws_defaults.yml" ]
  roles:
    - init
    - php5-cli
    - apache
    - php5
    - mysql
    - composer
    - phpcommon
    - app
    - node