---
- stat: path=/etc/php/{{ php.version }}/apache2/php.ini
  register: modphp

- stat: path=/etc/php/{{ php.version }}/cli/php.ini
  register: phpcli

- include: php-cli.yml
  when: phpcli.stat.exists

- include: mod-php.yml
  when: modphp.stat.exists
