---
mysql:
  ppa: "deb http://repo.mysql.com/apt/debian/ stretch mysql-5.7"
  key_server: "keyserver.ubuntu.com"
  key_id: "467B942D3A79BD29"
  version: "5.7"
  root_password: 'root'
  packages: [
    mysql-server,
    mysql-client,
    python-mysqldb
  ]