---
mysql:
  ppa: "deb http://repo.mysql.com/apt/debian/ stretch mysql-5.7"
  key_server: "keyserver.ubuntu.com"
  key_id: "8C718D3B5072E1F5"
  version: "5.7"
  root_password: 'root'
  packages: [
    mysql-server,
    mysql-client,
    python-mysqldb
  ]